// <auto-generated />
using Chatbot.Modules.Knowledge.Brokers.Storage;
using Chatbot.Modules.Knowledge.Brokers.Storage.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(StorageBroker), typeof(StorageBrokerModel))]
