// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Chatbot.Modules.Knowledge.Brokers.Storage.CompiledModels
{
    public partial class StorageBrokerModel
    {
        private StorageBrokerModel()
            : base(skipDetectChanges: false, modelId: new Guid("cccfd803-b556-43b9-9e4b-bcc10c2cb30a"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var documentChunk = DocumentChunkEntityType.Create(this);
            var knowledgeDocument = KnowledgeDocumentEntityType.Create(this);

            DocumentChunkEntityType.CreateAnnotations(documentChunk);
            KnowledgeDocumentEntityType.CreateAnnotations(knowledgeDocument);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.9");
            AddAnnotation("Relational:DefaultSchema", "knowledge");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
