// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Chatbot.Modules.Knowledge.Brokers.Storage.CompiledModels
{
    public partial class StorageBrokerModel
    {
        private StorageBrokerModel()
            : base(skipDetectChanges: false, modelId: new Guid("73feacd7-4f60-44d5-b895-8944df22ec72"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var documentChunk = DocumentChunkEntityType.Create(this);
            var knowledgeDocument = KnowledgeDocumentEntityType.Create(this);
            var inboxState = InboxStateEntityType.Create(this);
            var outboxMessage = OutboxMessageEntityType.Create(this);
            var outboxState = OutboxStateEntityType.Create(this);

            OutboxMessageEntityType.CreateForeignKey1(outboxMessage, outboxState);
            OutboxMessageEntityType.CreateForeignKey2(outboxMessage, inboxState);

            DocumentChunkEntityType.CreateAnnotations(documentChunk);
            KnowledgeDocumentEntityType.CreateAnnotations(knowledgeDocument);
            InboxStateEntityType.CreateAnnotations(inboxState);
            OutboxMessageEntityType.CreateAnnotations(outboxMessage);
            OutboxStateEntityType.CreateAnnotations(outboxState);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.8");
            AddAnnotation("Relational:DefaultSchema", "knowledge");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
