// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions } from "@pinia/colada";

import { serializeQueryKeyValue } from "../client";
import { client } from "../client.gen";
import { getIdentity, type Options, streamCompletion } from "../sdk.gen";
import type {
  GetIdentityData,
  GetIdentityResponse,
  StreamCompletionData,
  StreamCompletionError,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "path"> & {
    _id: string;
    baseUrl?: _JSONValue;
    body?: _JSONValue;
    query?: _JSONValue;
    tags?: _JSONValue;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (tags) {
    params.tags = tags as unknown as _JSONValue;
  }
  if (options?.body !== undefined) {
    const normalizedBody = serializeQueryKeyValue(options.body);
    if (normalizedBody !== undefined) {
      params.body = normalizedBody;
    }
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query !== undefined) {
    const normalizedQuery = serializeQueryKeyValue(options.query);
    if (normalizedQuery !== undefined) {
      params.query = normalizedQuery;
    }
  }
  return [params];
};

export const getIdentityQueryKey = (options?: Options<GetIdentityData>) =>
  createQueryKey("getIdentity", options, ["Chatbot.Api"]);

export const getIdentityQuery = defineQueryOptions<
  Options<GetIdentityData>,
  GetIdentityResponse,
  Error
>((options?: Options<GetIdentityData>) => ({
  key: getIdentityQueryKey(options),
  query: async (context) => {
    const { data } = await getIdentity({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const streamCompletionQueryKey = (
  options: Options<StreamCompletionData>,
) => createQueryKey("streamCompletion", options, ["Chat"]);

/**
 * Stream AI completion tokens via Server-Sent Events.
 *
 * Opens an SSE connection and emits individual AI token chunks as they are produced by the language model. Each event carries a JSON-serialized SseToken payload. A final event with IsFinal=true signals stream completion.
 */
export const streamCompletionQuery = defineQueryOptions<
  Options<StreamCompletionData>,
  unknown,
  StreamCompletionError
>((options: Options<StreamCompletionData>) => ({
  key: streamCompletionQueryKey(options),
  query: async (context) => {
    const { data } = await streamCompletion({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));
