// This file is auto-generated by @hey-api/openapi-ts

import {
  type _JSONValue,
  defineQueryOptions,
  type UseMutationOptions,
} from "@pinia/colada";

import { serializeQueryKeyValue } from "../client";
import { client } from "../client.gen";
import {
  createChatMessage,
  createChatSession,
  deleteChatMessage,
  deleteChatSession,
  getAllChatMessages,
  getAllChatSessions,
  getChatMessageById,
  getChatSessionById,
  getIdentity,
  type Options,
  streamCompletion,
  updateChatMessage,
  updateChatSession,
} from "../sdk.gen";
import type {
  CreateChatMessageData,
  CreateChatMessageError,
  CreateChatMessageResponse,
  CreateChatSessionData,
  CreateChatSessionError,
  CreateChatSessionResponse,
  DeleteChatMessageData,
  DeleteChatMessageResponse,
  DeleteChatSessionData,
  DeleteChatSessionResponse,
  GetAllChatMessagesData,
  GetAllChatMessagesError,
  GetAllChatMessagesResponse,
  GetAllChatSessionsData,
  GetAllChatSessionsError,
  GetAllChatSessionsResponse,
  GetChatMessageByIdData,
  GetChatMessageByIdResponse,
  GetChatSessionByIdData,
  GetChatSessionByIdResponse,
  GetIdentityData,
  GetIdentityResponse,
  StreamCompletionData,
  StreamCompletionError,
  UpdateChatMessageData,
  UpdateChatMessageError,
  UpdateChatMessageResponse,
  UpdateChatSessionData,
  UpdateChatSessionError,
  UpdateChatSessionResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "path"> & {
    _id: string;
    baseUrl?: _JSONValue;
    body?: _JSONValue;
    query?: _JSONValue;
    tags?: _JSONValue;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (tags) {
    params.tags = tags as unknown as _JSONValue;
  }
  if (options?.body !== undefined) {
    const normalizedBody = serializeQueryKeyValue(options.body);
    if (normalizedBody !== undefined) {
      params.body = normalizedBody;
    }
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query !== undefined) {
    const normalizedQuery = serializeQueryKeyValue(options.query);
    if (normalizedQuery !== undefined) {
      params.query = normalizedQuery;
    }
  }
  return [params];
};

export const getIdentityQueryKey = (options?: Options<GetIdentityData>) =>
  createQueryKey("getIdentity", options, ["Chatbot.Api"]);

export const getIdentityQuery = defineQueryOptions<
  Options<GetIdentityData>,
  GetIdentityResponse,
  Error
>((options?: Options<GetIdentityData>) => ({
  key: getIdentityQueryKey(options),
  query: async (context) => {
    const { data } = await getIdentity({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const streamCompletionQueryKey = (
  options: Options<StreamCompletionData>,
) => createQueryKey("streamCompletion", options, ["Chat"]);

/**
 * Stream AI completion tokens via Server-Sent Events.
 *
 * Opens an SSE connection and emits individual AI token chunks as they are produced by the language model. Each event carries a JSON-serialized SseToken payload. A final event with IsFinal=true signals stream completion.
 */
export const streamCompletionQuery = defineQueryOptions<
  Options<StreamCompletionData>,
  unknown,
  StreamCompletionError
>((options: Options<StreamCompletionData>) => ({
  key: streamCompletionQueryKey(options),
  query: async (context) => {
    const { data } = await streamCompletion({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const getAllChatSessionsQueryKey = (
  options?: Options<GetAllChatSessionsData>,
) => createQueryKey("getAllChatSessions", options, ["ChatSessionEndpoints"]);

/**
 * Retrieve all chat sessions.
 */
export const getAllChatSessionsQuery = defineQueryOptions<
  Options<GetAllChatSessionsData>,
  GetAllChatSessionsResponse,
  GetAllChatSessionsError
>((options?: Options<GetAllChatSessionsData>) => ({
  key: getAllChatSessionsQueryKey(options),
  query: async (context) => {
    const { data } = await getAllChatSessions({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Create a new chat session.
 */
export const createChatSessionMutation = (
  options?: Partial<Options<CreateChatSessionData>>,
): UseMutationOptions<
  CreateChatSessionResponse,
  Options<CreateChatSessionData>,
  CreateChatSessionError
> => ({
  mutation: async (vars) => {
    const { data } = await createChatSession({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Delete a chat session.
 */
export const deleteChatSessionMutation = (
  options?: Partial<Options<DeleteChatSessionData>>,
): UseMutationOptions<
  DeleteChatSessionResponse,
  Options<DeleteChatSessionData>,
  Error
> => ({
  mutation: async (vars) => {
    const { data } = await deleteChatSession({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getChatSessionByIdQueryKey = (
  options: Options<GetChatSessionByIdData>,
) => createQueryKey("getChatSessionById", options, ["ChatSessionEndpoints"]);

/**
 * Retrieve a chat session by ID.
 */
export const getChatSessionByIdQuery = defineQueryOptions<
  Options<GetChatSessionByIdData>,
  GetChatSessionByIdResponse,
  Error
>((options: Options<GetChatSessionByIdData>) => ({
  key: getChatSessionByIdQueryKey(options),
  query: async (context) => {
    const { data } = await getChatSessionById({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Update a chat session.
 */
export const updateChatSessionMutation = (
  options?: Partial<Options<UpdateChatSessionData>>,
): UseMutationOptions<
  UpdateChatSessionResponse,
  Options<UpdateChatSessionData>,
  UpdateChatSessionError
> => ({
  mutation: async (vars) => {
    const { data } = await updateChatSession({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getAllChatMessagesQueryKey = (
  options?: Options<GetAllChatMessagesData>,
) => createQueryKey("getAllChatMessages", options, ["ChatMessageEndpoints"]);

/**
 * Retrieve all chat messages.
 */
export const getAllChatMessagesQuery = defineQueryOptions<
  Options<GetAllChatMessagesData>,
  GetAllChatMessagesResponse,
  GetAllChatMessagesError
>((options?: Options<GetAllChatMessagesData>) => ({
  key: getAllChatMessagesQueryKey(options),
  query: async (context) => {
    const { data } = await getAllChatMessages({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Create a new chat message.
 */
export const createChatMessageMutation = (
  options?: Partial<Options<CreateChatMessageData>>,
): UseMutationOptions<
  CreateChatMessageResponse,
  Options<CreateChatMessageData>,
  CreateChatMessageError
> => ({
  mutation: async (vars) => {
    const { data } = await createChatMessage({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Delete a chat message.
 */
export const deleteChatMessageMutation = (
  options?: Partial<Options<DeleteChatMessageData>>,
): UseMutationOptions<
  DeleteChatMessageResponse,
  Options<DeleteChatMessageData>,
  Error
> => ({
  mutation: async (vars) => {
    const { data } = await deleteChatMessage({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getChatMessageByIdQueryKey = (
  options: Options<GetChatMessageByIdData>,
) => createQueryKey("getChatMessageById", options, ["ChatMessageEndpoints"]);

/**
 * Retrieve a chat message by ID.
 */
export const getChatMessageByIdQuery = defineQueryOptions<
  Options<GetChatMessageByIdData>,
  GetChatMessageByIdResponse,
  Error
>((options: Options<GetChatMessageByIdData>) => ({
  key: getChatMessageByIdQueryKey(options),
  query: async (context) => {
    const { data } = await getChatMessageById({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Update a chat message.
 */
export const updateChatMessageMutation = (
  options?: Partial<Options<UpdateChatMessageData>>,
): UseMutationOptions<
  UpdateChatMessageResponse,
  Options<UpdateChatMessageData>,
  UpdateChatMessageError
> => ({
  mutation: async (vars) => {
    const { data } = await updateChatMessage({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});
