// This file is auto-generated by @hey-api/openapi-ts

export { getIdentity, type Options, streamCompletion } from "./sdk.gen";
export type {
  ClientOptions,
  GetIdentityData,
  GetIdentityResponse,
  GetIdentityResponses,
  ProblemDetails,
  StreamCompletionData,
  StreamCompletionError,
  StreamCompletionErrors,
  StreamCompletionResponses,
} from "./types.gen";
