// This file is auto-generated by @hey-api/openapi-ts

import * as v from "valibot";

import type {
  Client,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  GetIdentityData,
  GetIdentityResponses,
  StreamCompletionData,
  StreamCompletionErrors,
  StreamCompletionResponses,
} from "./types.gen";
import { vGetIdentityResponse, vStreamCompletionQuery } from "./valibot.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getIdentity = <ThrowOnError extends boolean = false>(
  options?: Options<GetIdentityData, ThrowOnError>,
): RequestResult<GetIdentityResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetIdentityResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await v.parseAsync(
        v.object({
          body: v.optional(v.never()),
          path: v.optional(v.never()),
          query: v.optional(v.never()),
        }),
        data,
      ),
    responseTransformer: async (data) =>
      await v.parseAsync(vGetIdentityResponse, data),
    url: "/identity",
    ...options,
  });

/**
 * Stream AI completion tokens via Server-Sent Events.
 *
 * Opens an SSE connection and emits individual AI token chunks as they are produced by the language model. Each event carries a JSON-serialized SseToken payload. A final event with IsFinal=true signals stream completion.
 */
export const streamCompletion = <ThrowOnError extends boolean = false>(
  options: Options<StreamCompletionData, ThrowOnError>,
): RequestResult<
  StreamCompletionResponses,
  StreamCompletionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    StreamCompletionResponses,
    StreamCompletionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await v.parseAsync(
        v.object({
          body: v.optional(v.never()),
          path: v.optional(v.never()),
          query: vStreamCompletionQuery,
        }),
        data,
      ),
    url: "/api/chat/completions/stream",
    ...options,
  });
