// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number | string;
  detail?: null | string;
  instance?: null | string;
};

export type GetIdentityData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/identity";
};

export type GetIdentityResponses = {
  /**
   * OK
   */
  200: string;
};

export type GetIdentityResponse =
  GetIdentityResponses[keyof GetIdentityResponses];

export type StreamCompletionData = {
  body?: never;
  path?: never;
  query: {
    prompt: string;
  };
  url: "/api/chat/completions/stream";
};

export type StreamCompletionErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type StreamCompletionError =
  StreamCompletionErrors[keyof StreamCompletionErrors];

export type StreamCompletionResponses = {
  /**
   * OK
   */
  200: unknown;
};
