// This file is auto-generated by @hey-api/openapi-ts

import * as v from "valibot";

export const vProblemDetails = v.object({
  type: v.nullish(v.string()),
  title: v.nullish(v.string()),
  status: v.nullish(
    v.union([
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(
          -2147483648,
          "Invalid value: Expected int32 to be >= -2147483648",
        ),
        v.maxValue(
          2147483647,
          "Invalid value: Expected int32 to be <= 2147483647",
        ),
      ),
      v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/)),
    ]),
  ),
  detail: v.nullish(v.string()),
  instance: v.nullish(v.string()),
});

/**
 * OK
 */
export const vGetIdentityResponse = v.string();

export const vStreamCompletionQuery = v.object({
  prompt: v.string(),
});
