// <auto-generated />
using System;
using System.Reflection;
using Chatbot.Modules.Chat.Models.Sessions;
using Chatbot.Shared.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Chatbot.Modules.Chat.Brokers.Storage.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ChatSessionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Chatbot.Modules.Chat.Models.Sessions.ChatSession",
                typeof(ChatSession),
                baseEntityType,
                propertyCount: 9,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(ChatSessionId),
                propertyInfo: typeof(ChatSession).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatSession).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            id.SetValueConverter(new ValueConverter<ChatSessionId, Guid>(
                Guid (ChatSessionId id) => id.Value,
                ChatSessionId (Guid value) => new ChatSessionId(value)));
            id.SetSentinelFromProviderValue(new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var channelProvider = runtimeEntityType.AddProperty(
                "ChannelProvider",
                typeof(ChannelProvider),
                propertyInfo: typeof(ChatSession).GetProperty("ChannelProvider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatSession).GetField("<ChannelProvider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(string));
            channelProvider.SetSentinelFromProviderValue("WebWidget");
            channelProvider.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            channelProvider.AddAnnotation("Relational:ColumnName", "channel_provider");

            var createdDate = runtimeEntityType.AddProperty(
                "CreatedDate",
                typeof(Instant),
                propertyInfo: typeof(ChatSession).GetProperty("CreatedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatSession).GetField("<CreatedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: NodaTime.Instant.FromUnixTimeTicks(0L));
            createdDate.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdDate.AddAnnotation("Relational:ColumnName", "created_date");

            var customerIdentifier = runtimeEntityType.AddProperty(
                "CustomerIdentifier",
                typeof(string),
                propertyInfo: typeof(ChatSession).GetProperty("CustomerIdentifier", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatSession).GetField("<CustomerIdentifier>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            customerIdentifier.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            customerIdentifier.AddAnnotation("Relational:ColumnName", "customer_identifier");

            var externalReferenceId = runtimeEntityType.AddProperty(
                "ExternalReferenceId",
                typeof(string),
                propertyInfo: typeof(ChatSession).GetProperty("ExternalReferenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatSession).GetField("<ExternalReferenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            externalReferenceId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            externalReferenceId.AddAnnotation("Relational:ColumnName", "external_reference_id");

            var operatorId = runtimeEntityType.AddProperty(
                "OperatorId",
                typeof(OperatorId?),
                propertyInfo: typeof(ChatSession).GetProperty("OperatorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatSession).GetField("<OperatorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            operatorId.SetValueConverter(new ValueConverter<OperatorId?, Guid?>(
                Guid? (OperatorId? id) => (id.HasValue ? ((Guid? )(id.Value.Value)) : null),
                OperatorId? (Guid? value) => (value.HasValue ? ((OperatorId? )(new OperatorId(value.Value))) : null)));
            operatorId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            operatorId.AddAnnotation("Relational:ColumnName", "operator_id");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(ChatSessionStatus),
                propertyInfo: typeof(ChatSession).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatSession).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            status.SetSentinelFromProviderValue(0);
            status.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            status.AddAnnotation("Relational:ColumnName", "status");

            var tenantId = runtimeEntityType.AddProperty(
                "TenantId",
                typeof(TenantId),
                propertyInfo: typeof(ChatSession).GetProperty("TenantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatSession).GetField("<TenantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            tenantId.SetValueConverter(new ValueConverter<TenantId, Guid>(
                Guid (TenantId id) => id.Value,
                TenantId (Guid value) => new TenantId(value)));
            tenantId.SetSentinelFromProviderValue(new Guid("00000000-0000-0000-0000-000000000000"));
            tenantId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            tenantId.AddAnnotation("Relational:ColumnName", "tenant_id");

            var updatedDate = runtimeEntityType.AddProperty(
                "UpdatedDate",
                typeof(Instant),
                propertyInfo: typeof(ChatSession).GetProperty("UpdatedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatSession).GetField("<UpdatedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: NodaTime.Instant.FromUnixTimeTicks(0L));
            updatedDate.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            updatedDate.AddAnnotation("Relational:ColumnName", "updated_date");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_chat_sessions");

            var index = runtimeEntityType.AddIndex(
                new[] { channelProvider, externalReferenceId });
            index.AddAnnotation("Relational:Name", "idx_sessions_channel");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "chat");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "chat_sessions");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
