// <auto-generated />
using System;
using System.Reflection;
using Chatbot.Modules.Chat.Models.Sessions;
using Chatbot.Shared.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Chatbot.Modules.Chat.Brokers.Storage.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ChatMessageEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Chatbot.Modules.Chat.Models.Sessions.ChatMessage",
                typeof(ChatMessage),
                baseEntityType,
                propertyCount: 10,
                navigationCount: 2,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(ChatMessageId),
                propertyInfo: typeof(ChatMessage).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatMessage).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            id.SetValueConverter(new ValueConverter<ChatMessageId, Guid>(
                Guid (ChatMessageId id) => id.Value,
                ChatMessageId (Guid value) => new ChatMessageId(value)));
            id.SetSentinelFromProviderValue(new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var approvedBy = runtimeEntityType.AddProperty(
                "ApprovedBy",
                typeof(Guid?),
                propertyInfo: typeof(ChatMessage).GetProperty("ApprovedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatMessage).GetField("<ApprovedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            approvedBy.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            approvedBy.AddAnnotation("Relational:ColumnName", "approved_by");

            var content = runtimeEntityType.AddProperty(
                "Content",
                typeof(string),
                propertyInfo: typeof(ChatMessage).GetProperty("Content", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatMessage).GetField("<Content>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            content.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            content.AddAnnotation("Relational:ColumnName", "content");

            var createdDate = runtimeEntityType.AddProperty(
                "CreatedDate",
                typeof(Instant),
                propertyInfo: typeof(ChatMessage).GetProperty("CreatedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatMessage).GetField("<CreatedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: NodaTime.Instant.FromUnixTimeTicks(0L));
            createdDate.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdDate.AddAnnotation("Relational:ColumnName", "created_date");

            var isAiGenerated = runtimeEntityType.AddProperty(
                "IsAiGenerated",
                typeof(bool),
                propertyInfo: typeof(ChatMessage).GetProperty("IsAiGenerated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatMessage).GetField("<IsAiGenerated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isAiGenerated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            isAiGenerated.AddAnnotation("Relational:ColumnName", "is_ai_generated");

            var sender = runtimeEntityType.AddProperty(
                "Sender",
                typeof(MessageSender),
                propertyInfo: typeof(ChatMessage).GetProperty("Sender", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatMessage).GetField("<Sender>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            sender.SetSentinelFromProviderValue(0);
            sender.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            sender.AddAnnotation("Relational:ColumnName", "sender");

            var sessionId = runtimeEntityType.AddProperty(
                "SessionId",
                typeof(ChatSessionId),
                propertyInfo: typeof(ChatMessage).GetProperty("SessionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatMessage).GetField("<SessionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            sessionId.SetValueConverter(new ValueConverter<ChatSessionId, Guid>(
                Guid (ChatSessionId id) => id.Value,
                ChatSessionId (Guid value) => new ChatSessionId(value)));
            sessionId.SetSentinelFromProviderValue(new Guid("00000000-0000-0000-0000-000000000000"));
            sessionId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            sessionId.AddAnnotation("Relational:ColumnName", "session_id");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(MessageStatus),
                propertyInfo: typeof(ChatMessage).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatMessage).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(string));
            status.SetSentinelFromProviderValue("Sent");
            status.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            status.AddAnnotation("Relational:ColumnName", "status");

            var tenantId = runtimeEntityType.AddProperty(
                "TenantId",
                typeof(TenantId),
                propertyInfo: typeof(ChatMessage).GetProperty("TenantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatMessage).GetField("<TenantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            tenantId.SetValueConverter(new ValueConverter<TenantId, Guid>(
                Guid (TenantId id) => id.Value,
                TenantId (Guid value) => new TenantId(value)));
            tenantId.SetSentinelFromProviderValue(new Guid("00000000-0000-0000-0000-000000000000"));
            tenantId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            tenantId.AddAnnotation("Relational:ColumnName", "tenant_id");

            var updatedDate = runtimeEntityType.AddProperty(
                "UpdatedDate",
                typeof(Instant),
                propertyInfo: typeof(ChatMessage).GetProperty("UpdatedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChatMessage).GetField("<UpdatedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: NodaTime.Instant.FromUnixTimeTicks(0L));
            updatedDate.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            updatedDate.AddAnnotation("Relational:ColumnName", "updated_date");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_chat_messages");

            var index = runtimeEntityType.AddIndex(
                new[] { sessionId });
            index.AddAnnotation("Relational:Name", "idx_messages_session");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "chat");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "chat_messages");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
