// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Chatbot.Modules.Chat.Brokers.Storage.CompiledModels
{
    public partial class StorageBrokerModel
    {
        private StorageBrokerModel()
            : base(skipDetectChanges: false, modelId: new Guid("76f65308-5d46-40db-8e3b-bc0fed84177c"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var aiMetadata = AiMetadataEntityType.Create(this);
            var chatMessage = ChatMessageEntityType.Create(this);
            var chatSession = ChatSessionEntityType.Create(this);
            var citation = CitationEntityType.Create(this);

            AiMetadataEntityType.CreateForeignKey1(aiMetadata, chatMessage);
            CitationEntityType.CreateForeignKey1(citation, chatMessage);

            AiMetadataEntityType.CreateAnnotations(aiMetadata);
            ChatMessageEntityType.CreateAnnotations(chatMessage);
            ChatSessionEntityType.CreateAnnotations(chatSession);
            CitationEntityType.CreateAnnotations(citation);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.8");
            AddAnnotation("Relational:DefaultSchema", "chat");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
