// <auto-generated />
using System;
using Chatbot.Modules.Chat.Brokers.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chatbot.Modules.Chat.Migrations
{
    [DbContext(typeof(StorageBroker))]
    partial class StorageBrokerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chat")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chatbot.Modules.Chat.Models.Sessions.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Instant>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ai_generated");

                    b.Property<int>("Sender")
                        .HasColumnType("integer")
                        .HasColumnName("sender");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Instant>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_messages_session");

                    b.ToTable("chat_messages", "chat");
                });

            modelBuilder.Entity("Chatbot.Modules.Chat.Models.Sessions.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChannelProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_provider");

                    b.Property<Instant>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CustomerIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_identifier");

                    b.Property<string>("ExternalReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("external_reference_id");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Instant>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_chat_sessions");

                    b.HasIndex("ChannelProvider", "ExternalReferenceId")
                        .HasDatabaseName("idx_sessions_channel");

                    b.ToTable("chat_sessions", "chat");
                });

            modelBuilder.Entity("Chatbot.Modules.Chat.Models.Sessions.ChatMessage", b =>
                {
                    b.OwnsOne("Chatbot.Modules.Chat.Models.Sessions.AiMetadata", "AiMetadata", b1 =>
                        {
                            b1.Property<Guid>("ChatMessageId");

                            b1.Property<int>("CompletionTokens");

                            b1.Property<double>("LatencyMs");

                            b1.Property<string>("ModelName")
                                .IsRequired();

                            b1.Property<int>("PromptTokens");

                            b1.Property<int>("TotalTokens");

                            b1.HasKey("ChatMessageId");

                            b1.ToTable("chat_messages", "chat");

                            b1
                                .ToJson("ai_metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChatMessageId")
                                .HasConstraintName("fk_chat_messages_chat_messages_id");
                        });

                    b.OwnsMany("Chatbot.Modules.Chat.Models.Sessions.Citation", "Citations", b1 =>
                        {
                            b1.Property<Guid>("ChatMessageId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double>("Score");

                            b1.Property<string>("Snippet")
                                .IsRequired();

                            b1.Property<string>("SourceUrl")
                                .IsRequired();

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.HasKey("ChatMessageId", "__synthesizedOrdinal");

                            b1.ToTable("chat_messages", "chat");

                            b1
                                .ToJson("citations")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChatMessageId")
                                .HasConstraintName("fk_chat_messages_chat_messages_chat_message_id");
                        });

                    b.Navigation("AiMetadata");

                    b.Navigation("Citations");
                });
#pragma warning restore 612, 618
        }
    }
}
