// <auto-generated />
using System;
using System.Reflection;
using MassTransit.EntityFrameworkCoreIntegration;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Chatbot.Modules.Identity.Brokers.Storage.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class OutboxMessageEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MassTransit.EntityFrameworkCoreIntegration.OutboxMessage",
                typeof(OutboxMessage),
                baseEntityType,
                propertyCount: 21,
                foreignKeyCount: 2,
                unnamedIndexCount: 4,
                keyCount: 1);

            var sequenceNumber = runtimeEntityType.AddProperty(
                "SequenceNumber",
                typeof(long),
                propertyInfo: typeof(OutboxMessage).GetProperty("SequenceNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<SequenceNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            sequenceNumber.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            sequenceNumber.AddAnnotation("Relational:ColumnName", "sequence_number");

            var body = runtimeEntityType.AddProperty(
                "Body",
                typeof(string),
                propertyInfo: typeof(OutboxMessage).GetProperty("Body", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<Body>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            body.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            body.AddAnnotation("Relational:ColumnName", "body");

            var contentType = runtimeEntityType.AddProperty(
                "ContentType",
                typeof(string),
                propertyInfo: typeof(OutboxMessage).GetProperty("ContentType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<ContentType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 256);
            contentType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            contentType.AddAnnotation("Relational:ColumnName", "content_type");

            var conversationId = runtimeEntityType.AddProperty(
                "ConversationId",
                typeof(Guid?),
                propertyInfo: typeof(OutboxMessage).GetProperty("ConversationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<ConversationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            conversationId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            conversationId.AddAnnotation("Relational:ColumnName", "conversation_id");

            var correlationId = runtimeEntityType.AddProperty(
                "CorrelationId",
                typeof(Guid?),
                propertyInfo: typeof(OutboxMessage).GetProperty("CorrelationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<CorrelationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            correlationId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            correlationId.AddAnnotation("Relational:ColumnName", "correlation_id");

            var destinationAddress = runtimeEntityType.AddProperty(
                "DestinationAddress",
                typeof(Uri),
                propertyInfo: typeof(OutboxMessage).GetProperty("DestinationAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<DestinationAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            destinationAddress.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            destinationAddress.AddAnnotation("Relational:ColumnName", "destination_address");

            var enqueueTime = runtimeEntityType.AddProperty(
                "EnqueueTime",
                typeof(DateTime?),
                propertyInfo: typeof(OutboxMessage).GetProperty("EnqueueTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<EnqueueTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            enqueueTime.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            enqueueTime.AddAnnotation("Relational:ColumnName", "enqueue_time");

            var expirationTime = runtimeEntityType.AddProperty(
                "ExpirationTime",
                typeof(DateTime?),
                propertyInfo: typeof(OutboxMessage).GetProperty("ExpirationTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<ExpirationTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            expirationTime.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            expirationTime.AddAnnotation("Relational:ColumnName", "expiration_time");

            var faultAddress = runtimeEntityType.AddProperty(
                "FaultAddress",
                typeof(Uri),
                propertyInfo: typeof(OutboxMessage).GetProperty("FaultAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<FaultAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            faultAddress.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            faultAddress.AddAnnotation("Relational:ColumnName", "fault_address");

            var headers = runtimeEntityType.AddProperty(
                "Headers",
                typeof(string),
                propertyInfo: typeof(OutboxMessage).GetProperty("Headers", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<Headers>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            headers.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            headers.AddAnnotation("Relational:ColumnName", "headers");

            var inboxConsumerId = runtimeEntityType.AddProperty(
                "InboxConsumerId",
                typeof(Guid?),
                propertyInfo: typeof(OutboxMessage).GetProperty("InboxConsumerId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<InboxConsumerId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            inboxConsumerId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            inboxConsumerId.AddAnnotation("Relational:ColumnName", "inbox_consumer_id");

            var inboxMessageId = runtimeEntityType.AddProperty(
                "InboxMessageId",
                typeof(Guid?),
                propertyInfo: typeof(OutboxMessage).GetProperty("InboxMessageId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<InboxMessageId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            inboxMessageId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            inboxMessageId.AddAnnotation("Relational:ColumnName", "inbox_message_id");

            var initiatorId = runtimeEntityType.AddProperty(
                "InitiatorId",
                typeof(Guid?),
                propertyInfo: typeof(OutboxMessage).GetProperty("InitiatorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<InitiatorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            initiatorId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            initiatorId.AddAnnotation("Relational:ColumnName", "initiator_id");

            var messageId = runtimeEntityType.AddProperty(
                "MessageId",
                typeof(Guid),
                propertyInfo: typeof(OutboxMessage).GetProperty("MessageId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<MessageId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            messageId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            messageId.AddAnnotation("Relational:ColumnName", "message_id");

            var messageType = runtimeEntityType.AddProperty(
                "MessageType",
                typeof(string),
                propertyInfo: typeof(OutboxMessage).GetProperty("MessageType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<MessageType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            messageType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            messageType.AddAnnotation("Relational:ColumnName", "message_type");

            var outboxId = runtimeEntityType.AddProperty(
                "OutboxId",
                typeof(Guid?),
                propertyInfo: typeof(OutboxMessage).GetProperty("OutboxId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<OutboxId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            outboxId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            outboxId.AddAnnotation("Relational:ColumnName", "outbox_id");

            var properties = runtimeEntityType.AddProperty(
                "Properties",
                typeof(string),
                propertyInfo: typeof(OutboxMessage).GetProperty("Properties", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<Properties>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            properties.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            properties.AddAnnotation("Relational:ColumnName", "properties");

            var requestId = runtimeEntityType.AddProperty(
                "RequestId",
                typeof(Guid?),
                propertyInfo: typeof(OutboxMessage).GetProperty("RequestId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<RequestId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            requestId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            requestId.AddAnnotation("Relational:ColumnName", "request_id");

            var responseAddress = runtimeEntityType.AddProperty(
                "ResponseAddress",
                typeof(Uri),
                propertyInfo: typeof(OutboxMessage).GetProperty("ResponseAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<ResponseAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            responseAddress.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            responseAddress.AddAnnotation("Relational:ColumnName", "response_address");

            var sentTime = runtimeEntityType.AddProperty(
                "SentTime",
                typeof(DateTime),
                propertyInfo: typeof(OutboxMessage).GetProperty("SentTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<SentTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            sentTime.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            sentTime.AddAnnotation("Relational:ColumnName", "sent_time");

            var sourceAddress = runtimeEntityType.AddProperty(
                "SourceAddress",
                typeof(Uri),
                propertyInfo: typeof(OutboxMessage).GetProperty("SourceAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxMessage).GetField("<SourceAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            sourceAddress.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            sourceAddress.AddAnnotation("Relational:ColumnName", "source_address");

            var key = runtimeEntityType.AddKey(
                new[] { sequenceNumber });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_outbox_message");

            var index = runtimeEntityType.AddIndex(
                new[] { enqueueTime });
            index.AddAnnotation("Relational:Name", "ix_outbox_message_enqueue_time");

            var index0 = runtimeEntityType.AddIndex(
                new[] { expirationTime });
            index0.AddAnnotation("Relational:Name", "ix_outbox_message_expiration_time");

            var index1 = runtimeEntityType.AddIndex(
                new[] { outboxId, sequenceNumber },
                unique: true);
            index1.AddAnnotation("Relational:Name", "ix_outbox_message_outbox_id_sequence_number");

            var index2 = runtimeEntityType.AddIndex(
                new[] { inboxMessageId, inboxConsumerId, sequenceNumber },
                unique: true);
            index2.AddAnnotation("Relational:Name", "ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("OutboxId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("OutboxId") }),
                principalEntityType);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_outbox_message_outbox_state_outbox_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("InboxMessageId"), declaringEntityType.FindProperty("InboxConsumerId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("MessageId"), principalEntityType.FindProperty("ConsumerId") }),
                principalEntityType);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "identity");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "outbox_message");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
