// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Chatbot.Modules.Identity.Brokers.Storage.CompiledModels
{
    public partial class StorageBrokerModel
    {
        private StorageBrokerModel()
            : base(skipDetectChanges: false, modelId: new Guid("bc049a0a-fa3f-404c-b461-e79bf1577f21"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var user = UserEntityType.Create(this);
            var inboxState = InboxStateEntityType.Create(this);
            var outboxMessage = OutboxMessageEntityType.Create(this);
            var outboxState = OutboxStateEntityType.Create(this);

            OutboxMessageEntityType.CreateForeignKey1(outboxMessage, outboxState);
            OutboxMessageEntityType.CreateForeignKey2(outboxMessage, inboxState);

            UserEntityType.CreateAnnotations(user);
            InboxStateEntityType.CreateAnnotations(inboxState);
            OutboxMessageEntityType.CreateAnnotations(outboxMessage);
            OutboxStateEntityType.CreateAnnotations(outboxState);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.8");
            AddAnnotation("Relational:DefaultSchema", "identity");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
