// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Chatbot.Modules.Identity.Brokers.Storage.CompiledModels
{
    public partial class StorageBrokerModel
    {
        private StorageBrokerModel()
            : base(skipDetectChanges: false, modelId: new Guid("1cbc71d9-b133-40b8-bdc9-6da5c8371166"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var user = UserEntityType.Create(this);

            UserEntityType.CreateAnnotations(user);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.8");
            AddAnnotation("Relational:DefaultSchema", "identity");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
